name: "Update Pull Request"
on:
  # event trigger: when the PR is merged
  pull_request:
    types: [ closed ]

env:
  FRESHRELEASE_TICKET_ID: 0
  FRESHRELEASE_TICKET_KEY: 0
  PULL_REQUEST_NUMBER: 0

jobs:
  pr_review_tracker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get the PR Number and set it in the env variable
      run: |
          echo $GITHUB_REF
          PULL_NUMBER=$(echo "$GITHUB_REF"| awk -F / '{print $3}' )
          echo "::set-env name=PULL_REQUEST_NUMBER::$PULL_NUMBER"
