
name: "Freshrelease auto-ticket generator"
on:
  pull_request:
    branches: [ master ]
    types: [ opened ]
  
jobs:
  update-pr-with-freshrelease-id:
    runs-on: ubuntu-latest
    steps:
    # Extract PR number 
    - name: Get Pr number
      id: pull_request_number
      run: |
          PULL_NUMBER=$(echo "$GITHUB_REF"| awk -F / '{print $3}' )
          echo "::set-output name=PULL_REQUEST_NUMBER::$PULL_NUMBER"
          
    # Get the pull request data
    - name: Get Pull Request Data
      id: pull_request_data
      uses: simpleactions/get-pull-request@v1.0.0
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        pull_number: "${{ steps.pull_request_number.outputs.PULL_REQUEST_NUMBER }}"
        
    # Create Freshrelease Ticket
    - uses: satak/webrequest-action@master
      id: freshrelease-ticket
      with:
        url: https://freshworks.freshrelease.com/API/issues
        method: POST
        payload: '{"title": "${{ steps.pull_request_data.outputs.title }}", "name": "${{ steps.pull_request_data.outputs.title }}", "description": "Refer to the Pr for details : https://github.com/freshdesk/api-tools/pull/${{ steps.pull_request_number.outputs.PULL_REQUEST_NUMBER }}", "issue_type_id": 45978, "epic_id": 217897, "parent_id": 217897, "status_id": 18, "priority_id": 8, "reporter_id": 2748}'
        headers: '{"authorization": "Token token=${{ secrets.FRESHRELEASE_TOKEN }}", "Content-Type": "application/json", "Accept": "application/json"}'
    
    # Extract Freshrelease ticket ID for updating in the PR
    - name: get-request output
      id: fr_ticket_id
      shell: pwsh
      run: |
        $output = '${{ steps.freshrelease-ticket.outputs.output }}' | ConvertFrom-Json
        $key = $output.data.issue.key
        echo "::set-output name=FRESHRELEASE_TICKET_ID::$key"
        
    # Update PR details with the created reshrelease ticket ID
    - uses: tzkhan/pr-update-action@v1.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: '[\s\S]*'
        title-template: '[${{ steps.fr_ticket_id.outputs.FRESHRELEASE_TICKET_ID }}]'
        body-template: 'Freshrelease Ticket: [${{ steps.fr_ticket_id.outputs.FRESHRELEASE_TICKET_ID }}](https://freshworks.freshrelease.com/API/issues/${{ steps.fr_ticket_id.outputs.FRESHRELEASE_TICKET_ID }})'
